export const DEFAULT_EXERCISES = [
  // Chest
  ["Flat Barbell Bench Press", "Chest"], ["Incline Dumbbell Press", "Chest"],
  ["Incline Barbell Bench Press", "Chest"], ["Cable Fly", "Chest"],
  ["Push Up", "Chest"], ["Dips", "Chest"], ["Pec Deck", "Chest"],
  ["Decline Barbell Bench Press", "Chest"], ["Decline Dumbbell Press", "Chest"],
  ["Flat Dumbbell Press", "Chest"], ["Dumbbell Fly", "Chest"],
  ["Incline Cable Fly", "Chest"], ["Low Cable Fly", "Chest"],
  ["Cable Crossover", "Chest"], ["Machine Chest Press", "Chest"],
  ["Incline Machine Press", "Chest"], ["Smith Machine Bench Press", "Chest"],
  ["Chest Dip", "Chest"], ["Svend Press", "Chest"], ["Decline Push Up", "Chest"],
  // Back
  ["Deadlift", "Back"], ["Barbell Row", "Back"], ["Lat Pulldown", "Back"],
  ["Pull Up", "Back"], ["Seated Cable Row", "Back"], ["T-Bar Row", "Back"],
  ["Single Arm Dumbbell Row", "Back"], ["Face Pull", "Back"],
  ["Chin Up", "Back"], ["Sumo Deadlift", "Back"], ["Rack Pull", "Back"],
  ["Hyperextension", "Back"], ["Dumbbell Pullover", "Back"],
  ["Cable Pullover", "Back"], ["Straight Arm Pulldown", "Back"],
  ["Wide Grip Lat Pulldown", "Back"], ["Close Grip Lat Pulldown", "Back"],
  ["Chest Supported Row", "Back"], ["Inverted Row", "Back"],
  ["Meadows Row", "Back"], ["Pendlay Row", "Back"],
  ["Smith Machine Row", "Back"], ["Seal Row", "Back"],
  // Legs
  ["Barbell Squat", "Legs"], ["Leg Press", "Legs"], ["Romanian Deadlift", "Legs"],
  ["Leg Extension", "Legs"], ["Lying Leg Curl", "Legs"], ["Standing Calf Raise", "Legs"],
  ["Hack Squat", "Legs"], ["Bulgarian Split Squat", "Legs"], ["Seated Calf Raise", "Legs"],
  ["Front Squat", "Legs"], ["Goblet Squat", "Legs"], ["Sumo Squat", "Legs"],
  ["Hip Thrust", "Legs"], ["Glute Bridge", "Legs"], ["Lunge", "Legs"],
  ["Walking Lunge", "Legs"], ["Reverse Lunge", "Legs"], ["Step Up", "Legs"],
  ["Box Jump", "Legs"], ["Leg Press Calf Raise", "Legs"],
  ["Smith Machine Squat", "Legs"], ["Seated Leg Curl", "Legs"],
  ["Nordic Hamstring Curl", "Legs"], ["Pistol Squat", "Legs"],
  ["Abductor Machine", "Legs"], ["Adductor Machine", "Legs"],
  ["Sissy Squat", "Legs"], ["Cable Kickback", "Legs"],
  ["Donkey Calf Raise", "Legs"], ["Single Leg Press", "Legs"],
  // Shoulders
  ["Overhead Press", "Shoulders"], ["Dumbbell Shoulder Press", "Shoulders"],
  ["Lateral Raise", "Shoulders"], ["Arnold Press", "Shoulders"],
  ["Rear Delt Fly", "Shoulders"], ["Upright Row", "Shoulders"],
  ["Cable Lateral Raise", "Shoulders"], ["Dumbbell Front Raise", "Shoulders"],
  ["Barbell Front Raise", "Shoulders"], ["Cable Front Raise", "Shoulders"],
  ["Machine Shoulder Press", "Shoulders"], ["Reverse Pec Deck", "Shoulders"],
  ["Bent Over Lateral Raise", "Shoulders"], ["Barbell Shrug", "Shoulders"],
  ["Dumbbell Shrug", "Shoulders"], ["Cable Shrug", "Shoulders"],
  ["Landmine Press", "Shoulders"], ["Push Press", "Shoulders"],
  ["Bradford Press", "Shoulders"],
  // Biceps
  ["Barbell Curl", "Biceps"], ["Dumbbell Curl", "Biceps"], ["Hammer Curl", "Biceps"],
  ["Preacher Curl", "Biceps"], ["Cable Curl", "Biceps"], ["Incline Dumbbell Curl", "Biceps"],
  ["Concentration Curl", "Biceps"], ["Spider Curl", "Biceps"],
  ["Zottman Curl", "Biceps"], ["Reverse Curl", "Biceps"],
  ["EZ Bar Curl", "Biceps"], ["Machine Curl", "Biceps"],
  ["Cable Rope Hammer Curl", "Biceps"], ["Cross Body Hammer Curl", "Biceps"],
  ["Scott Curl", "Biceps"], ["Bayesian Curl", "Biceps"],
  // Triceps
  ["Cable Pushdown", "Triceps"], ["Skull Crusher", "Triceps"],
  ["Overhead Triceps Extension", "Triceps"], ["Close-Grip Bench Press", "Triceps"],
  ["Diamond Push Up", "Triceps"], ["Tricep Kickback", "Triceps"],
  ["Tricep Dip", "Triceps"], ["JM Press", "Triceps"], ["Tate Press", "Triceps"],
  ["Reverse Grip Pushdown", "Triceps"], ["EZ Bar Skull Crusher", "Triceps"],
  ["Single Arm Cable Pushdown", "Triceps"],
  ["Cable Overhead Tricep Extension", "Triceps"],
  // Core
  ["Plank", "Core"], ["Hanging Leg Raise", "Core"], ["Cable Crunch", "Core"],
  ["Russian Twist", "Core"], ["Ab Rollout", "Core"], ["Sit Up", "Core"],
  ["Dead Bug", "Core"], ["Bird Dog", "Core"], ["Side Plank", "Core"],
  ["V-Up", "Core"], ["Leg Raise", "Core"], ["Bicycle Crunch", "Core"],
  ["Mountain Climbers", "Core"], ["Flutter Kicks", "Core"],
  ["Hollow Body Hold", "Core"], ["Dragon Flag", "Core"],
  ["Pallof Press", "Core"], ["Decline Sit Up", "Core"],
  ["Oblique Crunch", "Core"], ["Woodchop", "Core"],
  ["Toe Touch", "Core"], ["Windshield Wiper", "Core"],
  // Cardio
  ["Treadmill Run", "Cardio"], ["Stationary Bike", "Cardio"], ["Rowing Machine", "Cardio"],
  ["Jump Rope", "Cardio"], ["Stair Climber", "Cardio"], ["Elliptical", "Cardio"],
  ["Burpees", "Cardio"], ["Battle Ropes", "Cardio"], ["Assault Bike", "Cardio"],
  ["Sled Push", "Cardio"], ["Sled Pull", "Cardio"], ["Ski Erg", "Cardio"],
  ["Kettlebell Swing", "Cardio"], ["Swimming", "Cardio"], ["Walking", "Cardio"],
  ["Cycling", "Cardio"], ["Sprint", "Cardio"], ["Box Step", "Cardio"],
  // Added from free-exercise-db (https://github.com/yuhonas/free-exercise-db, MIT licensed)
  // Chest (new)
  ["Alternating Floor Press", "Chest"], ["Around The Worlds", "Chest"],
  ["Barbell Bench Press - Medium Grip", "Chest"], ["Barbell Guillotine Bench Press", "Chest"],
  ["Barbell Incline Bench Press - Medium Grip", "Chest"], ["Bench Press - With Bands", "Chest"],
  ["Bent-Arm Dumbbell Pullover", "Chest"], ["Bodyweight Flyes", "Chest"], ["Butterfly", "Chest"],
  ["Cable Chest Press", "Chest"], ["Cable Iron Cross", "Chest"], ["Chain Press", "Chest"],
  ["Chest Push (multiple response)", "Chest"], ["Chest Push (single response)", "Chest"],
  ["Chest Push from 3 point stance", "Chest"], ["Chest Push with Run Release", "Chest"],
  ["Clock Push-Up", "Chest"], ["Cross Over - With Bands", "Chest"],
  ["Decline Dumbbell Bench Press", "Chest"], ["Decline Dumbbell Flyes", "Chest"],
  ["Decline Push-Up", "Chest"], ["Decline Smith Press", "Chest"],
  ["Dips - Chest Version", "Chest"], ["Drop Push", "Chest"], ["Dumbbell Bench Press", "Chest"],
  ["Dumbbell Bench Press with Neutral Grip", "Chest"], ["Dumbbell Flyes", "Chest"],
  ["Extended Range One-Arm Kettlebell Floor Press", "Chest"], ["Flat Bench Cable Flyes", "Chest"],
  ["Forward Drag with Press", "Chest"], ["Front Raise And Pullover", "Chest"],
  ["Hammer Grip Incline DB Bench Press", "Chest"], ["Heavy Bag Thrust", "Chest"],
  ["Incline Cable Chest Press", "Chest"], ["Incline Cable Flye", "Chest"],
  ["Incline Dumbbell Bench With Palms Facing In", "Chest"], ["Incline Dumbbell Flyes", "Chest"],
  ["Incline Dumbbell Flyes - With A Twist", "Chest"], ["Incline Push-Up", "Chest"],
  ["Incline Push-Up Depth Jump", "Chest"], ["Incline Push-Up Medium", "Chest"],
  ["Incline Push-Up Reverse Grip", "Chest"], ["Incline Push-Up Wide", "Chest"],
  ["Isometric Chest Squeezes", "Chest"], ["Isometric Wipers", "Chest"],
  ["Leg-Over Floor Press", "Chest"], ["Leverage Chest Press", "Chest"],
  ["Leverage Decline Chest Press", "Chest"], ["Leverage Incline Chest Press", "Chest"],
  ["Low Cable Crossover", "Chest"], ["Machine Bench Press", "Chest"],
  ["Medicine Ball Chest Pass", "Chest"], ["Neck Press", "Chest"],
  ["One Arm Dumbbell Bench Press", "Chest"], ["One-Arm Flat Bench Dumbbell Flye", "Chest"],
  ["One-Arm Kettlebell Floor Press", "Chest"], ["Plyo Kettlebell Pushups", "Chest"],
  ["Plyo Push-up", "Chest"], ["Push Up to Side Plank", "Chest"], ["Push-Up Wide", "Chest"],
  ["Push-Ups With Feet Elevated", "Chest"], ["Push-Ups With Feet On An Exercise Ball", "Chest"],
  ["Pushups", "Chest"], ["Pushups (Close and Wide Hand Positions)", "Chest"],
  ["Single-Arm Cable Crossover", "Chest"], ["Single-Arm Push-Up", "Chest"],
  ["Smith Machine Decline Press", "Chest"], ["Smith Machine Incline Bench Press", "Chest"],
  ["Standing Cable Chest Press", "Chest"], ["Straight-Arm Dumbbell Pullover", "Chest"],
  ["Suspended Push-Up", "Chest"], ["Wide-Grip Barbell Bench Press", "Chest"],
  ["Wide-Grip Decline Barbell Bench Press", "Chest"],
  ["Wide-Grip Decline Barbell Pullover", "Chest"],
  // Back (new)
  ["Alternating Kettlebell Row", "Back"], ["Alternating Renegade Row", "Back"],
  ["Atlas Stone Trainer", "Back"], ["Atlas Stones", "Back"], ["Axle Deadlift", "Back"],
  ["Band Assisted Pull-Up", "Back"], ["Barbell Deadlift", "Back"],
  ["Bent Over Barbell Row", "Back"], ["Bent Over One-Arm Long Bar Row", "Back"],
  ["Bent Over Two-Arm Long Bar Row", "Back"], ["Bent Over Two-Dumbbell Row", "Back"],
  ["Bent Over Two-Dumbbell Row With Palms In", "Back"], ["Bent-Arm Barbell Pullover", "Back"],
  ["Bodyweight Mid Row", "Back"], ["Cable Incline Pushdown", "Back"],
  ["Catch and Overhead Throw", "Back"], ["Chin-Up", "Back"],
  ["Close-Grip Front Lat Pulldown", "Back"], ["Deadlift with Bands", "Back"],
  ["Deadlift with Chains", "Back"], ["Deficit Deadlift", "Back"], ["Dumbbell Incline Row", "Back"],
  ["Elevated Cable Rows", "Back"], ["Full Range-Of-Motion Lat Pulldown", "Back"],
  ["Gironda Sternum Chins", "Back"], ["Hyperextensions (Back Extensions)", "Back"],
  ["Hyperextensions With No Hyperextension Bench", "Back"], ["Incline Bench Pull", "Back"],
  ["Inverted Row with Straps", "Back"], ["Keg Load", "Back"], ["Kipping Muscle Up", "Back"],
  ["Kneeling High Pulley Row", "Back"], ["Kneeling Single-Arm High Pulley Row", "Back"],
  ["Leverage High Row", "Back"], ["Leverage Iso Row", "Back"], ["London Bridges", "Back"],
  ["Lying Cambered Barbell Row", "Back"], ["Lying T-Bar Row", "Back"],
  ["Middle Back Shrug", "Back"], ["Mixed Grip Chin", "Back"], ["Muscle Up", "Back"],
  ["One Arm Chin-Up", "Back"], ["One Arm Lat Pulldown", "Back"], ["One-Arm Dumbbell Row", "Back"],
  ["One-Arm Kettlebell Row", "Back"], ["One-Arm Long Bar Row", "Back"], ["Overhead Slam", "Back"],
  ["Pullups", "Back"], ["Rack Pull with Bands", "Back"], ["Rack Pulls", "Back"],
  ["Reverse Band Deadlift", "Back"], ["Reverse Grip Bent-Over Rows", "Back"],
  ["Rocky Pull-Ups/Pulldowns", "Back"], ["Rope Climb", "Back"],
  ["Rope Straight-Arm Pulldown", "Back"], ["Seated Cable Rows", "Back"],
  ["Seated Good Mornings", "Back"], ["Seated One-arm Cable Pulley Rows", "Back"],
  ["Shotgun Row", "Back"], ["Side To Side Chins", "Back"], ["Sled Row", "Back"],
  ["Smith Machine Bent Over Row", "Back"], ["Stiff Leg Barbell Good Morning", "Back"],
  ["Straight Bar Bench Mid Rows", "Back"], ["Straight-Arm Pulldown", "Back"],
  ["Suspended Row", "Back"], ["T-Bar Row with Handle", "Back"], ["Two-Arm Kettlebell Row", "Back"],
  ["Underhand Cable Pulldowns", "Back"], ["V-Bar Pulldown", "Back"], ["V-Bar Pullup", "Back"],
  ["Weighted Ball Hyperextension", "Back"], ["Weighted Pull Ups", "Back"],
  ["Wide-Grip Lat Pulldown", "Back"], ["Wide-Grip Pulldown Behind The Neck", "Back"],
  ["Wide-Grip Rear Pull-Up", "Back"],
  // Legs (new)
  ["Alternate Leg Diagonal Bound", "Legs"], ["Alternating Hang Clean", "Legs"],
  ["Backward Drag", "Legs"], ["Balance Board", "Legs"], ["Ball Leg Curl", "Legs"],
  ["Band Good Morning", "Legs"], ["Band Good Morning (Pull Through)", "Legs"],
  ["Band Hip Adductions", "Legs"], ["Barbell Full Squat", "Legs"],
  ["Barbell Glute Bridge", "Legs"], ["Barbell Hack Squat", "Legs"], ["Barbell Hip Thrust", "Legs"],
  ["Barbell Lunge", "Legs"], ["Barbell Seated Calf Raise", "Legs"],
  ["Barbell Side Split Squat", "Legs"], ["Barbell Squat To A Bench", "Legs"],
  ["Barbell Step Ups", "Legs"], ["Barbell Walking Lunge", "Legs"],
  ["Bear Crawl Sled Drags", "Legs"], ["Bench Jump", "Legs"], ["Bench Sprint", "Legs"],
  ["Bodyweight Squat", "Legs"], ["Bodyweight Walking Lunge", "Legs"],
  ["Box Jump (Multiple Response)", "Legs"], ["Box Skip", "Legs"], ["Box Squat", "Legs"],
  ["Box Squat with Bands", "Legs"], ["Box Squat with Chains", "Legs"],
  ["Butt Lift (Bridge)", "Legs"], ["Cable Deadlifts", "Legs"], ["Cable Hip Adduction", "Legs"],
  ["Calf Press", "Legs"], ["Calf Press On The Leg Press Machine", "Legs"],
  ["Calf Raise On A Dumbbell", "Legs"], ["Calf Raises - With Bands", "Legs"],
  ["Car Deadlift", "Legs"], ["Carioca Quick Step", "Legs"], ["Chair Squat", "Legs"],
  ["Clean", "Legs"], ["Clean Deadlift", "Legs"], ["Clean from Blocks", "Legs"],
  ["Clean Pull", "Legs"], ["Conan's Wheel", "Legs"], ["Depth Jump Leap", "Legs"],
  ["Donkey Calf Raises", "Legs"], ["Double Kettlebell Alternating Hang Clean", "Legs"],
  ["Double Leg Butt Kick", "Legs"], ["Downward Facing Balance", "Legs"],
  ["Dumbbell Clean", "Legs"], ["Dumbbell Lunges", "Legs"], ["Dumbbell Rear Lunge", "Legs"],
  ["Dumbbell Seated Box Jump", "Legs"], ["Dumbbell Seated One-Leg Calf Raise", "Legs"],
  ["Dumbbell Squat", "Legs"], ["Dumbbell Squat To A Bench", "Legs"], ["Dumbbell Step Ups", "Legs"],
  ["Elevated Back Lunge", "Legs"], ["Fast Skipping", "Legs"], ["Floor Glute-Ham Raise", "Legs"],
  ["Frankenstein Squat", "Legs"], ["Freehand Jump Squat", "Legs"], ["Front Barbell Squat", "Legs"],
  ["Front Barbell Squat To A Bench", "Legs"], ["Front Box Jump", "Legs"],
  ["Front Cone Hops (or hurdle hops)", "Legs"], ["Front Squat (Clean Grip)", "Legs"],
  ["Front Squats With Two Kettlebells", "Legs"], ["Glute Ham Raise", "Legs"],
  ["Glute Kickback", "Legs"], ["Good Morning", "Legs"], ["Good Morning off Pins", "Legs"],
  ["Hang Clean", "Legs"], ["Hang Clean - Below the Knees", "Legs"], ["Hang Snatch", "Legs"],
  ["Hang Snatch - Below Knees", "Legs"], ["Hanging Bar Good Morning", "Legs"],
  ["Heaving Snatch Balance", "Legs"], ["Hip Extension with Bands", "Legs"],
  ["Hip Flexion with Band", "Legs"], ["Hip Lift with Band", "Legs"], ["Hurdle Hops", "Legs"],
  ["Jefferson Squats", "Legs"], ["Jerk Dip Squat", "Legs"], ["Kettlebell Dead Clean", "Legs"],
  ["Kettlebell Hang Clean", "Legs"], ["Kettlebell One-Legged Deadlift", "Legs"],
  ["Kettlebell Pistol Squat", "Legs"], ["Knee Tuck Jump", "Legs"], ["Kneeling Jump Squat", "Legs"],
  ["Kneeling Squat", "Legs"], ["Lateral Bound", "Legs"], ["Lateral Box Jump", "Legs"],
  ["Lateral Cone Hops", "Legs"], ["Leg Extensions", "Legs"], ["Leg Lift", "Legs"],
  ["Leverage Deadlift", "Legs"], ["Linear 3-Part Start Technique", "Legs"],
  ["Linear Acceleration Wall Drill", "Legs"], ["Linear Depth Jump", "Legs"],
  ["Lunge Pass Through", "Legs"], ["Lunge Sprint", "Legs"], ["Lying Leg Curls", "Legs"],
  ["Lying Machine Squat", "Legs"], ["Monster Walk", "Legs"], ["Moving Claw Series", "Legs"],
  ["Muscle Snatch", "Legs"], ["Narrow Stance Hack Squats", "Legs"],
  ["Narrow Stance Leg Press", "Legs"], ["Narrow Stance Squats", "Legs"],
  ["Natural Glute Ham Raise", "Legs"], ["Olympic Squat", "Legs"],
  ["One Leg Barbell Squat", "Legs"], ["One-Arm Kettlebell Clean", "Legs"],
  ["One-Arm Kettlebell Swings", "Legs"], ["One-Arm Open Palm Kettlebell Clean", "Legs"],
  ["One-Arm Overhead Kettlebell Squats", "Legs"], ["One-Arm Side Deadlift", "Legs"],
  ["One-Legged Cable Kickback", "Legs"], ["Open Palm Kettlebell Clean", "Legs"],
  ["Overhead Squat", "Legs"], ["Physioball Hip Bridge", "Legs"],
  ["Platform Hamstring Slides", "Legs"], ["Plie Dumbbell Squat", "Legs"], ["Power Clean", "Legs"],
  ["Power Clean from Blocks", "Legs"], ["Power Jerk", "Legs"], ["Power Snatch", "Legs"],
  ["Power Snatch from Blocks", "Legs"], ["Power Stairs", "Legs"],
  ["Prone Manual Hamstring", "Legs"], ["Pull Through", "Legs"], ["Quick Leap", "Legs"],
  ["Reverse Band Box Squat", "Legs"], ["Reverse Band Power Squat", "Legs"],
  ["Reverse Band Sumo Deadlift", "Legs"], ["Reverse Hyperextension", "Legs"],
  ["Rickshaw Deadlift", "Legs"], ["Rocket Jump", "Legs"], ["Rocking Standing Calf Raise", "Legs"],
  ["Romanian Deadlift from Deficit", "Legs"], ["Sandbag Load", "Legs"], ["Scissors Jump", "Legs"],
  ["Seated Band Hamstring Curl", "Legs"], ["Side Hop-Sprint", "Legs"],
  ["Side Standing Long Jump", "Legs"], ["Side to Side Box Shuffle", "Legs"],
  ["Single Leg Butt Kick", "Legs"], ["Single Leg Glute Bridge", "Legs"],
  ["Single Leg Push-off", "Legs"], ["Single-Cone Sprint Drill", "Legs"],
  ["Single-Leg High Box Squat", "Legs"], ["Single-Leg Hop Progression", "Legs"],
  ["Single-Leg Lateral Hop", "Legs"], ["Single-Leg Leg Extension", "Legs"],
  ["Single-Leg Stride Jump", "Legs"], ["Sled Drag - Harness", "Legs"],
  ["Smith Machine Calf Raise", "Legs"], ["Smith Machine Hang Power Clean", "Legs"],
  ["Smith Machine Leg Press", "Legs"], ["Smith Machine Pistol Squat", "Legs"],
  ["Smith Machine Reverse Calf Raises", "Legs"], ["Smith Machine Stiff-Legged Deadlift", "Legs"],
  ["Smith Single-Leg Split Squat", "Legs"], ["Snatch", "Legs"], ["Snatch Balance", "Legs"],
  ["Snatch Deadlift", "Legs"], ["Snatch from Blocks", "Legs"], ["Snatch Pull", "Legs"],
  ["Speed Box Squat", "Legs"], ["Speed Squats", "Legs"], ["Split Clean", "Legs"],
  ["Split Jerk", "Legs"], ["Split Jump", "Legs"], ["Split Snatch", "Legs"],
  ["Split Squat with Dumbbells", "Legs"], ["Squat Jerk", "Legs"], ["Squat with Bands", "Legs"],
  ["Squat with Chains", "Legs"], ["Squat with Plate Movers", "Legs"],
  ["Squats - With Bands", "Legs"], ["Standing Barbell Calf Raise", "Legs"],
  ["Standing Calf Raises", "Legs"], ["Standing Dumbbell Calf Raise", "Legs"],
  ["Standing Leg Curl", "Legs"], ["Standing Long Jump", "Legs"], ["Star Jump", "Legs"],
  ["Step-up with Knee Raise", "Legs"], ["Stiff-Legged Barbell Deadlift", "Legs"],
  ["Stiff-Legged Dumbbell Deadlift", "Legs"], ["Stride Jump Crossover", "Legs"],
  ["Sumo Deadlift with Bands", "Legs"], ["Sumo Deadlift with Chains", "Legs"],
  ["Suspended Split Squat", "Legs"], ["Thigh Abductor", "Legs"], ["Thigh Adductor", "Legs"],
  ["Tire Flip", "Legs"], ["Trap Bar Deadlift", "Legs"], ["Vertical Swing", "Legs"],
  ["Weighted Jump Squat", "Legs"], ["Weighted Sissy Squat", "Legs"], ["Weighted Squat", "Legs"],
  ["Wide Stance Barbell Squat", "Legs"], ["Wide Stance Stiff Legs", "Legs"], ["Yoke Walk", "Legs"],
  ["Zercher Squats", "Legs"],
  // Shoulders (new)
  ["Alternating Cable Shoulder Press", "Shoulders"], ["Alternating Deltoid Raise", "Shoulders"],
  ["Alternating Kettlebell Press", "Shoulders"], ["Anti-Gravity Press", "Shoulders"],
  ["Arnold Dumbbell Press", "Shoulders"], ["Back Flyes - With Bands", "Shoulders"],
  ["Backward Medicine Ball Throw", "Shoulders"], ["Band Pull Apart", "Shoulders"],
  ["Barbell Incline Shoulder Raise", "Shoulders"], ["Barbell Rear Delt Row", "Shoulders"],
  ["Barbell Shoulder Press", "Shoulders"], ["Barbell Shrug Behind The Back", "Shoulders"],
  ["Battling Ropes", "Shoulders"],
  ["Bent Over Dumbbell Rear Delt Raise With Head On Bench", "Shoulders"],
  ["Bent Over Low-Pulley Side Lateral", "Shoulders"], ["Bradford/Rocky Presses", "Shoulders"],
  ["Cable Internal Rotation", "Shoulders"], ["Cable Rear Delt Fly", "Shoulders"],
  ["Cable Rope Rear-Delt Rows", "Shoulders"], ["Cable Seated Lateral Raise", "Shoulders"],
  ["Cable Shoulder Press", "Shoulders"], ["Cable Shrugs", "Shoulders"],
  ["Calf-Machine Shoulder Shrug", "Shoulders"], ["Car Drivers", "Shoulders"],
  ["Circus Bell", "Shoulders"], ["Clean and Jerk", "Shoulders"], ["Clean and Press", "Shoulders"],
  ["Clean Shrug", "Shoulders"], ["Crucifix", "Shoulders"], ["Cuban Press", "Shoulders"],
  ["Double Kettlebell Jerk", "Shoulders"], ["Double Kettlebell Push Press", "Shoulders"],
  ["Double Kettlebell Snatch", "Shoulders"], ["Dumbbell Incline Shoulder Raise", "Shoulders"],
  ["Dumbbell Lying One-Arm Rear Lateral Raise", "Shoulders"],
  ["Dumbbell Lying Rear Lateral Raise", "Shoulders"],
  ["Dumbbell One-Arm Shoulder Press", "Shoulders"], ["Dumbbell One-Arm Upright Row", "Shoulders"],
  ["Dumbbell Raise", "Shoulders"], ["Dumbbell Scaption", "Shoulders"],
  ["External Rotation", "Shoulders"], ["External Rotation with Band", "Shoulders"],
  ["External Rotation with Cable", "Shoulders"], ["Front Cable Raise", "Shoulders"],
  ["Front Dumbbell Raise", "Shoulders"], ["Front Incline Dumbbell Raise", "Shoulders"],
  ["Front Plate Raise", "Shoulders"], ["Front Two-Dumbbell Raise", "Shoulders"],
  ["Handstand Push-Ups", "Shoulders"], ["Internal Rotation with Band", "Shoulders"],
  ["Iron Cross", "Shoulders"], ["Isometric Neck Exercise - Front And Back", "Shoulders"],
  ["Isometric Neck Exercise - Sides", "Shoulders"], ["Jerk Balance", "Shoulders"],
  ["Kettlebell Arnold Press", "Shoulders"], ["Kettlebell Pirate Ships", "Shoulders"],
  ["Kettlebell Seated Press", "Shoulders"], ["Kettlebell Seesaw Press", "Shoulders"],
  ["Kettlebell Sumo High Pull", "Shoulders"], ["Kettlebell Thruster", "Shoulders"],
  ["Kettlebell Turkish Get-Up (Lunge style)", "Shoulders"],
  ["Kettlebell Turkish Get-Up (Squat style)", "Shoulders"], ["Kneeling Arm Drill", "Shoulders"],
  ["Landmine Linear Jammer", "Shoulders"], ["Lateral Raise - With Bands", "Shoulders"],
  ["Leverage Shoulder Press", "Shoulders"], ["Leverage Shrug", "Shoulders"],
  ["Log Lift", "Shoulders"], ["Low Pulley Row To Neck", "Shoulders"],
  ["Lying Face Down Plate Neck Resistance", "Shoulders"],
  ["Lying Face Up Plate Neck Resistance", "Shoulders"],
  ["Lying One-Arm Lateral Raise", "Shoulders"], ["Lying Rear Delt Raise", "Shoulders"],
  ["Machine Shoulder (Military) Press", "Shoulders"], ["Medicine Ball Scoop Throw", "Shoulders"],
  ["One-Arm Incline Lateral Raise", "Shoulders"],
  ["One-Arm Kettlebell Clean and Jerk", "Shoulders"], ["One-Arm Kettlebell Jerk", "Shoulders"],
  ["One-Arm Kettlebell Military Press To The Side", "Shoulders"],
  ["One-Arm Kettlebell Para Press", "Shoulders"], ["One-Arm Kettlebell Push Press", "Shoulders"],
  ["One-Arm Kettlebell Snatch", "Shoulders"], ["One-Arm Kettlebell Split Jerk", "Shoulders"],
  ["One-Arm Kettlebell Split Snatch", "Shoulders"], ["One-Arm Side Laterals", "Shoulders"],
  ["Power Partials", "Shoulders"], ["Push Press - Behind the Neck", "Shoulders"],
  ["Rack Delivery", "Shoulders"], ["Return Push from Stance", "Shoulders"],
  ["Reverse Flyes", "Shoulders"], ["Reverse Flyes With External Rotation", "Shoulders"],
  ["Reverse Machine Flyes", "Shoulders"], ["Scapular Pull-Up", "Shoulders"],
  ["Seated Barbell Military Press", "Shoulders"],
  ["Seated Bent-Over Rear Delt Raise", "Shoulders"], ["Seated Cable Shoulder Press", "Shoulders"],
  ["Seated Dumbbell Press", "Shoulders"], ["Seated Head Harness Neck Resistance", "Shoulders"],
  ["Seated Side Lateral Raise", "Shoulders"],
  ["See-Saw Press (Alternating Side Press)", "Shoulders"],
  ["Shoulder Press - With Bands", "Shoulders"], ["Side Lateral Raise", "Shoulders"],
  ["Side Laterals to Front Raise", "Shoulders"], ["Single Dumbbell Raise", "Shoulders"],
  ["Single-Arm Linear Jammer", "Shoulders"], ["Sled Overhead Backward Walk", "Shoulders"],
  ["Sled Reverse Flye", "Shoulders"], ["Smith Incline Shoulder Raise", "Shoulders"],
  ["Smith Machine Behind the Back Shrug", "Shoulders"],
  ["Smith Machine One-Arm Upright Row", "Shoulders"],
  ["Smith Machine Overhead Shoulder Press", "Shoulders"],
  ["Smith Machine Upright Row", "Shoulders"], ["Snatch Shrug", "Shoulders"],
  ["Standing Alternating Dumbbell Press", "Shoulders"],
  ["Standing Barbell Press Behind Neck", "Shoulders"], ["Standing Bradford Press", "Shoulders"],
  ["Standing Dumbbell Press", "Shoulders"],
  ["Standing Dumbbell Straight-Arm Front Delt Raise Above Head", "Shoulders"],
  ["Standing Dumbbell Upright Row", "Shoulders"],
  ["Standing Front Barbell Raise Over Head", "Shoulders"],
  ["Standing Low-Pulley Deltoid Raise", "Shoulders"], ["Standing Military Press", "Shoulders"],
  ["Standing Palm-In One-Arm Dumbbell Press", "Shoulders"],
  ["Standing Palms-In Dumbbell Press", "Shoulders"],
  ["Standing Two-Arm Overhead Throw", "Shoulders"],
  ["Straight Raises on Incline Bench", "Shoulders"], ["Two-Arm Kettlebell Clean", "Shoulders"],
  ["Two-Arm Kettlebell Jerk", "Shoulders"], ["Two-Arm Kettlebell Military Press", "Shoulders"],
  ["Upright Barbell Row", "Shoulders"], ["Upright Cable Row", "Shoulders"],
  ["Upright Row - With Bands", "Shoulders"],
  // Biceps (new)
  ["Alternate Hammer Curl", "Biceps"], ["Alternate Incline Dumbbell Curl", "Biceps"],
  ["Barbell Curls Lying Against An Incline", "Biceps"],
  ["Bottoms-Up Clean From The Hang Position", "Biceps"],
  ["Cable Hammer Curls - Rope Attachment", "Biceps"], ["Cable Preacher Curl", "Biceps"],
  ["Cable Wrist Curl", "Biceps"], ["Close-Grip EZ Bar Curl", "Biceps"],
  ["Close-Grip EZ-Bar Curl with Band", "Biceps"], ["Close-Grip Standing Barbell Curl", "Biceps"],
  ["Concentration Curls", "Biceps"], ["Drag Curl", "Biceps"],
  ["Dumbbell Alternate Bicep Curl", "Biceps"], ["Dumbbell Bicep Curl", "Biceps"],
  ["Dumbbell Lying Pronation", "Biceps"], ["Dumbbell Lying Supination", "Biceps"],
  ["Dumbbell Prone Incline Curl", "Biceps"], ["EZ-Bar Curl", "Biceps"],
  ["Farmer's Walk", "Biceps"], ["Finger Curls", "Biceps"],
  ["Flexor Incline Dumbbell Curls", "Biceps"], ["Hammer Curls", "Biceps"],
  ["High Cable Curls", "Biceps"], ["Incline Hammer Curls", "Biceps"],
  ["Incline Inner Biceps Curl", "Biceps"], ["Lying Cable Curl", "Biceps"],
  ["Lying Close-Grip Bar Curl On High Pulley", "Biceps"],
  ["Lying High Bench Barbell Curl", "Biceps"], ["Lying Supine Dumbbell Curl", "Biceps"],
  ["Machine Bicep Curl", "Biceps"], ["Machine Preacher Curls", "Biceps"],
  ["One Arm Dumbbell Preacher Curl", "Biceps"], ["Overhead Cable Curl", "Biceps"],
  ["Palms-Down Dumbbell Wrist Curl Over A Bench", "Biceps"],
  ["Palms-Down Wrist Curl Over A Bench", "Biceps"],
  ["Palms-Up Barbell Wrist Curl Over A Bench", "Biceps"],
  ["Palms-Up Dumbbell Wrist Curl Over A Bench", "Biceps"], ["Plate Pinch", "Biceps"],
  ["Preacher Hammer Dumbbell Curl", "Biceps"], ["Reverse Barbell Curl", "Biceps"],
  ["Reverse Barbell Preacher Curls", "Biceps"], ["Reverse Cable Curl", "Biceps"],
  ["Reverse Plate Curls", "Biceps"], ["Rickshaw Carry", "Biceps"],
  ["Seated Close-Grip Concentration Barbell Curl", "Biceps"], ["Seated Dumbbell Curl", "Biceps"],
  ["Seated Dumbbell Inner Biceps Curl", "Biceps"],
  ["Seated Dumbbell Palms-Down Wrist Curl", "Biceps"],
  ["Seated Dumbbell Palms-Up Wrist Curl", "Biceps"],
  ["Seated One-Arm Dumbbell Palms-Down Wrist Curl", "Biceps"],
  ["Seated One-Arm Dumbbell Palms-Up Wrist Curl", "Biceps"],
  ["Seated Palm-Up Barbell Wrist Curl", "Biceps"],
  ["Seated Palms-Down Barbell Wrist Curl", "Biceps"],
  ["Seated Two-Arm Palms-Up Low-Pulley Wrist Curl", "Biceps"],
  ["Standing Biceps Cable Curl", "Biceps"], ["Standing Concentration Curl", "Biceps"],
  ["Standing Dumbbell Reverse Curl", "Biceps"], ["Standing Inner-Biceps Curl", "Biceps"],
  ["Standing Olympic Plate Hand Squeeze", "Biceps"], ["Standing One-Arm Cable Curl", "Biceps"],
  ["Standing One-Arm Dumbbell Curl Over Incline Bench", "Biceps"],
  ["Standing Palms-Up Barbell Behind The Back Wrist Curl", "Biceps"],
  ["Two-Arm Dumbbell Preacher Curl", "Biceps"], ["Wide-Grip Standing Barbell Curl", "Biceps"],
  ["Wrist Roller", "Biceps"], ["Wrist Rotations with Straight Bar", "Biceps"],
  ["Zottman Preacher Curl", "Biceps"],
  // Triceps (new)
  ["Band Skull Crusher", "Triceps"], ["Bench Dips", "Triceps"],
  ["Bench Press - Powerlifting", "Triceps"], ["Bench Press with Chains", "Triceps"],
  ["Board Press", "Triceps"], ["Body Tricep Press", "Triceps"], ["Body-Up", "Triceps"],
  ["Cable Incline Triceps Extension", "Triceps"], ["Cable Lying Triceps Extension", "Triceps"],
  ["Cable One Arm Tricep Extension", "Triceps"],
  ["Cable Rope Overhead Triceps Extension", "Triceps"], ["Chain Handle Extension", "Triceps"],
  ["Close-Grip Barbell Bench Press", "Triceps"], ["Close-Grip Dumbbell Press", "Triceps"],
  ["Close-Grip EZ-Bar Press", "Triceps"], ["Close-Grip Push-Up off of a Dumbbell", "Triceps"],
  ["Decline Close-Grip Bench To Skull Crusher", "Triceps"],
  ["Decline Dumbbell Triceps Extension", "Triceps"],
  ["Decline EZ Bar Triceps Extension", "Triceps"], ["Dip Machine", "Triceps"],
  ["Dips - Triceps Version", "Triceps"], ["Dumbbell Floor Press", "Triceps"],
  ["Dumbbell One-Arm Triceps Extension", "Triceps"],
  ["Dumbbell Tricep Extension -Pronated Grip", "Triceps"], ["EZ-Bar Skullcrusher", "Triceps"],
  ["Floor Press", "Triceps"], ["Floor Press with Chains", "Triceps"],
  ["Incline Barbell Triceps Extension", "Triceps"], ["Incline Push-Up Close-Grip", "Triceps"],
  ["Kneeling Cable Triceps Extension", "Triceps"], ["Low Cable Triceps Extension", "Triceps"],
  ["Lying Close-Grip Barbell Triceps Extension Behind The Head", "Triceps"],
  ["Lying Close-Grip Barbell Triceps Press To Chin", "Triceps"],
  ["Lying Dumbbell Tricep Extension", "Triceps"], ["Lying Triceps Press", "Triceps"],
  ["Machine Triceps Extension", "Triceps"], ["One Arm Floor Press", "Triceps"],
  ["One Arm Pronated Dumbbell Triceps Extension", "Triceps"],
  ["One Arm Supinated Dumbbell Triceps Extension", "Triceps"], ["Parallel Bar Dip", "Triceps"],
  ["Pin Presses", "Triceps"], ["Push-Ups - Close Triceps Position", "Triceps"],
  ["Reverse Band Bench Press", "Triceps"], ["Reverse Grip Triceps Pushdown", "Triceps"],
  ["Reverse Triceps Bench Press", "Triceps"], ["Ring Dips", "Triceps"],
  ["Seated Bent-Over One-Arm Dumbbell Triceps Extension", "Triceps"],
  ["Seated Bent-Over Two-Arm Dumbbell Triceps Extension", "Triceps"],
  ["Seated Triceps Press", "Triceps"], ["Sled Overhead Triceps Extension", "Triceps"],
  ["Smith Machine Close-Grip Bench Press", "Triceps"], ["Speed Band Overhead Triceps", "Triceps"],
  ["Standing Bent-Over One-Arm Dumbbell Triceps Extension", "Triceps"],
  ["Standing Bent-Over Two-Arm Dumbbell Triceps Extension", "Triceps"],
  ["Standing Dumbbell Triceps Extension", "Triceps"],
  ["Standing Low-Pulley One-Arm Triceps Extension", "Triceps"],
  ["Standing One-Arm Dumbbell Triceps Extension", "Triceps"],
  ["Standing Overhead Barbell Triceps Extension", "Triceps"],
  ["Standing Towel Triceps Extension", "Triceps"], ["Supine Chest Throw", "Triceps"],
  ["Tricep Dumbbell Kickback", "Triceps"], ["Triceps Overhead Extension with Rope", "Triceps"],
  ["Triceps Pushdown", "Triceps"], ["Triceps Pushdown - Rope Attachment", "Triceps"],
  ["Triceps Pushdown - V-Bar Attachment", "Triceps"], ["Weighted Bench Dip", "Triceps"],
  // Core (new)
  ["3/4 Sit-Up", "Core"], ["Ab Crunch Machine", "Core"], ["Ab Roller", "Core"],
  ["Advanced Kettlebell Windmill", "Core"], ["Air Bike", "Core"],
  ["Alternate Heel Touchers", "Core"], ["Barbell Ab Rollout", "Core"],
  ["Barbell Ab Rollout - On Knees", "Core"], ["Barbell Rollout from Bench", "Core"],
  ["Barbell Side Bend", "Core"], ["Bent Press", "Core"], ["Bent-Knee Hip Raise", "Core"],
  ["Bosu Ball Cable Crunch With Side Bends", "Core"], ["Bottoms Up", "Core"], ["Butt-Ups", "Core"],
  ["Cable Judo Flip", "Core"], ["Cable Reverse Crunch", "Core"], ["Cable Russian Twists", "Core"],
  ["Cable Seated Crunch", "Core"], ["Cocoons", "Core"], ["Cross-Body Crunch", "Core"],
  ["Crunch - Hands Overhead", "Core"], ["Crunch - Legs On Exercise Ball", "Core"],
  ["Crunches", "Core"], ["Decline Crunch", "Core"], ["Decline Oblique Crunch", "Core"],
  ["Decline Reverse Crunch", "Core"], ["Double Kettlebell Windmill", "Core"],
  ["Dumbbell Side Bend", "Core"], ["Elbow to Knee", "Core"], ["Exercise Ball Crunch", "Core"],
  ["Exercise Ball Pull-In", "Core"], ["Flat Bench Leg Pull-In", "Core"],
  ["Flat Bench Lying Leg Raise", "Core"], ["Frog Sit-Ups", "Core"],
  ["Gorilla Chin/Crunch", "Core"], ["Hanging Pike", "Core"], ["Jackknife Sit-Up", "Core"],
  ["Janda Sit-Up", "Core"], ["Kettlebell Figure 8", "Core"],
  ["Kettlebell Pass Between The Legs", "Core"], ["Kettlebell Windmill", "Core"],
  ["Knee/Hip Raise On Parallel Bars", "Core"],
  ["Kneeling Cable Crunch With Alternating Oblique Twists", "Core"], ["Landmine 180's", "Core"],
  ["Leg Pull-In", "Core"], ["Medicine Ball Full Twist", "Core"], ["Oblique Crunches", "Core"],
  ["Oblique Crunches - On The Floor", "Core"], ["One-Arm High-Pulley Cable Side Bends", "Core"],
  ["One-Arm Medicine Ball Slam", "Core"], ["Otis-Up", "Core"],
  ["Pallof Press With Rotation", "Core"], ["Plate Twist", "Core"], ["Press Sit-Up", "Core"],
  ["Reverse Crunch", "Core"], ["Rope Crunch", "Core"], ["Seated Barbell Twist", "Core"],
  ["Seated Flat Bench Leg Pull-In", "Core"], ["Seated Leg Tucks", "Core"], ["Side Bridge", "Core"],
  ["Side Jackknife", "Core"], ["Sit-Up", "Core"], ["Sledgehammer Swings", "Core"],
  ["Smith Machine Hip Raise", "Core"], ["Spell Caster", "Core"], ["Spider Crawl", "Core"],
  ["Standing Cable Lift", "Core"], ["Standing Cable Wood Chop", "Core"],
  ["Standing Rope Crunch", "Core"], ["Supine One-Arm Overhead Throw", "Core"],
  ["Supine Two-Arm Overhead Throw", "Core"], ["Suspended Fallout", "Core"],
  ["Suspended Reverse Crunch", "Core"], ["Tuck Crunch", "Core"],
  ["Weighted Ball Side Bend", "Core"], ["Weighted Crunches", "Core"],
  ["Weighted Sit-Ups - With Bands", "Core"], ["Wind Sprints", "Core"],
  // Cardio (new)
  ["Bicycling", "Cardio"], ["Bicycling, Stationary", "Cardio"], ["Elliptical Trainer", "Cardio"],
  ["Jogging, Treadmill", "Cardio"], ["Prowler Sprint", "Cardio"], ["Recumbent Bike", "Cardio"],
  ["Rope Jumping", "Cardio"], ["Rowing, Stationary", "Cardio"], ["Running, Treadmill", "Cardio"],
  ["Skating", "Cardio"], ["Stairmaster", "Cardio"], ["Step Mill", "Cardio"],
  ["Trail Running/Walking", "Cardio"], ["Walking, Treadmill", "Cardio"],
].map(([name, group], i) => ({ id: "d" + i, name, group }));

// Exercises where weight tracking doesn't apply — only reps (or duration) matter.
export const BODYWEIGHT_EXERCISES = new Set([
  // Chest
  "Push Up", "Decline Push Up", "Diamond Push Up", "Dips", "Chest Dip",
  // Back
  "Pull Up", "Chin Up", "Inverted Row", "Hyperextension",
  // Legs
  "Box Jump", "Pistol Squat", "Glute Bridge", "Lunge", "Walking Lunge", "Reverse Lunge",
  // Triceps
  "Tricep Dip",
  // Core
  "Plank", "Side Plank", "Hanging Leg Raise", "Sit Up", "Decline Sit Up",
  "Leg Raise", "V-Up", "Dead Bug", "Bird Dog", "Hollow Body Hold",
  "Flutter Kicks", "Mountain Climbers", "Bicycle Crunch", "Toe Touch",
  "Windshield Wiper", "Oblique Crunch", "Dragon Flag",
  // Added from free-exercise-db
  "3/4 Sit-Up", "Air Bike", "Alternate Heel Touchers", "Bench Dips", "Bench Jump",
  "Bent-Knee Hip Raise", "Body Tricep Press", "Body-Up", "Bodyweight Squat", "Bottoms Up",
  "Butt Lift (Bridge)", "Butt-Ups", "Chin-Up", "Clock Push-Up",
  "Close-Grip Push-Up off of a Dumbbell", "Cocoons", "Cross-Body Crunch",
  "Crunch - Hands Overhead", "Crunch - Legs On Exercise Ball", "Crunches", "Decline Crunch",
  "Decline Oblique Crunch", "Decline Reverse Crunch", "Dips - Triceps Version",
  "Double Leg Butt Kick", "Elbow to Knee", "Fast Skipping", "Flat Bench Leg Pull-In",
  "Flat Bench Lying Leg Raise", "Freehand Jump Squat", "Frog Sit-Ups", "Glute Kickback",
  "Gorilla Chin/Crunch", "Handstand Push-Ups", "Hanging Pike",
  "Hyperextensions With No Hyperextension Bench", "Incline Push-Up", "Incline Push-Up Close-Grip",
  "Incline Push-Up Medium", "Incline Push-Up Reverse Grip", "Incline Push-Up Wide",
  "Isometric Chest Squeezes", "Isometric Neck Exercise - Front And Back",
  "Isometric Neck Exercise - Sides", "Isometric Wipers", "Jackknife Sit-Up", "Janda Sit-Up",
  "Knee Tuck Jump", "Lateral Bound", "Leg Lift", "Leg Pull-In", "Natural Glute Ham Raise",
  "Oblique Crunches", "Oblique Crunches - On The Floor", "Plyo Push-up", "Pullups",
  "Push Up to Side Plank", "Push-Up Wide", "Push-Ups - Close Triceps Position",
  "Push-Ups With Feet Elevated", "Pushups", "Pushups (Close and Wide Hand Positions)",
  "Reverse Crunch", "Rocket Jump", "Scissors Jump", "Seated Flat Bench Leg Pull-In",
  "Seated Leg Tucks", "Side Bridge", "Side Jackknife", "Single Leg Butt Kick",
  "Single Leg Glute Bridge", "Single-Arm Push-Up", "Sit-Up", "Spider Crawl", "Split Jump",
  "Standing Long Jump", "Standing Towel Triceps Extension", "Star Jump", "Step-up with Knee Raise",
  "Tuck Crunch", "V-Bar Pullup", "Wide-Grip Rear Pull-Up", "Wind Sprints",
]);

export const EMPTY_DATA = {
  workouts: {},
  customExercises: [],
  templates: [],
  goals: [],
  body: [],
  unit: "kg",
  weightStep: 2.5,
  lastSet: {},
  workoutNotes: {},
  meals: {},
  calorieGoal: 2000,
  macroGoals: { protein: 150, carbs: 200, fat: 65 },
};

export const STORAGE_KEY = "fitlog:v1";

export const loadData = () => {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return { ...EMPTY_DATA, ...JSON.parse(raw) };
  } catch (e) {
    console.error("Could not load saved data", e);
  }
  return EMPTY_DATA;
};
